---
- name: redhat | Installing EPEL repository
  yum:
    name: epel-release
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes

- name: redhat | Installing Shorewall
  yum:
    name:  shorewall
    state: present
    enablerepo: epel
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
