---
- name: redhat | Setting shorewall_version (Fedora)
  set_fact:
    shorewall_version: 52
  when: ansible_distribution == "Fedora"

- name: redhat | Installing EPEL repository
  yum:
    name: epel-release
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Shorewall (RHEL, Centos)
  yum:
    name:  shorewall
    state: present
    enablerepo: epel
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution == "RedHat" or ansible_distribution == "Centos"

- name: redhat | Installing Shorewall (Fedora)
  yum:
    name:  shorewall
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution == "Fedora"
