---
- name: redhat | Setting shorewall_version (Fedora)
  set_fact:
    shorewall_version: 52
  when: ansible_distribution | lower == "fedora"

- name: redhat | Installing EPEL repository
  yum:
    name: epel-release
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution | lower != "fedora"

- name: redhat | Installing Shorewall (RHEL, Centos)
  yum:
    name:  shorewall
    state: present
    enablerepo: base,extras,updates,epel
    disablerepo: "*"
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution | lower == "redhat" or ansible_distribution | lower == "centos"

- name: redhat | Installing Shorewall (Fedora)
  yum:
    name:  shorewall
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10
  become: yes
  when: ansible_distribution | lower == "fedora"

- name: redhat | Enabling Shorewall service
  systemd:
    name: shorewall
    enabled: yes
